### PR TITLE
Bug with Rails env variable from module

### PR DESCRIPTION
**Pull request by nlevchuk**
Hello. It's change working for me. You may include it into repository that more people could use it. Thanks.

### CODE REVIEW

**Comment by anlek** [comment]
+1
I've hit this issue as well.
The code provided by @nlevchuk has fixed the issue.

**Comment by aaronchi** [comment]
+1

**Comment by itspriddle** [comment]
I hit this today as well. @nlevchuk's fix worked for me. Any chance of getting it merged in a new release?

**Comment by andersondias** [comment]
I will try to merge it today :)

**Comment by andersondias** [comment]
Tests are broken, so I can't merge directly. The reason I didn't tried to use ::Rails.env.to_sym was because I don't want to close the gem to be Rails dependent.

I will try to handle this looking for how another gems has did this workaround.

**Comment by andersondias** [comment]
Fixed ;)

**Comment by andersondias** [comment]
New version launched, can you give it a try? Tks in advance

**Comment by itspriddle** [comment]
:+1: Works here, ty!

**Pull request closed without merging**
