### PR TITLE
fix the @@excluded_environments init

### PR DESCRIPTION
**Pull request by tubaxenor**
Just init the class variable to avoid raising :

```
NameError - uninitialized class variable @@excluded_environments in Sidekiq::Mailer:
```

### CODE REVIEW

**Comment by barmstrong** [comment]
:+1: fixed things for us

**Comment by asiniy** [comment]
This is good thing, but without rails4 supporting. I have a conflict:

```
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    sidekiq_mailer (>= 0) ruby depends on
      activesupport (~> 3.0) ruby

    rails (= 4.0.0) ruby depends on
      activesupport (4.0.0)

```

**Comment by cheshire137** [comment]
Could this get merged in? This error still exists in the latest gem.

**Comment by andersondias** [comment]
@tubaxenor I just picked up the final diff and generated a single commit on master. Thank you for your PR. :)

**Pull request closed without merging**
